### ISSUE TITLE
Various comments on reviewing draft

### ISSUE THREAD

**Issue by ericorth** [bemasc/ddr-forwarders#1]
2.1: "Recent estimates suggest..." Any ideas on a formal citation for this point? (I recognize that this is probably just acknowledging public but informal comments on the matter from Chrome, but it would be great if a similar point is made somewhere more formal that this draft could point to.)

6: I don't think this section goes into enough detail for somebody not already familiar with these issues to really understand the problem and the stuff that's not as bad as initially seems.  E.g., needs to more verbosely state that (in strict or relaxed) when an on-path attacker can intercept and manipulate queries/responses pre-upgrade, they can then easily block/manipulate DDR responses to prevent upgrade and continue mucking with the non-upgraded unecrypted requests/responses to have complete attacker visibility to DNS requests and control over DNS results.  Need to make clear that the only effective security difference is that only relaxed mode can trick client into doing an "upgrade" when it shouldn't and that the attacker can control the target of that "upgrade".

6.1.3: Should we point to Chrome and Firefox providers lists as an example of what a reputable provider list would look like? Seems especially relevant since being on one of those lists or similar is likely to actually be the mechanism used by prominent clients.

7: General solution for all these compatibility issues: I think we should note that clients may choose to involve user input before doing upgrade to allow the user to avoid upgrade if an incompatibility is known.  E.g., prompt the user before upgrade, or use the DDR signal only to add options to user-opt-in configuration UX.  Especially relevant since using the signal primarily to impact a configuration UX is what I have proposed for the initial Chrome behavior, to be followed later by autoupgrade once some time has passed in order to spread the message that behavior will change and parties will need to add resolver.arpa to their block lists if necessary.

7.1.1: Mostly just curiosity: Why does Firefox get the only citation for this behavior when Chrome essentially does the same thing by default in its current DoH autoupgrade?

7.3: Yeah, we need this section because otherwise somebody is bound to bring it up, but I remain unconvinced that this is actually an issue in practice (especially given my next comment on 7.3.1).  Can we maybe comment that it is unclear how much impact the caching actually has, maybe to see if anybody in ADD comments with any citations on the matter?

7.3.1: Are there any DNS clients that don't already maintain at least a basic cache.  Probably worth noting that this mitigation is already widely deployed.

**Comment by bemasc** [comment]
Thanks, I've incorporated most of those changes [here](https://github.com/bemasc/ddr-forwarders/commit/356b7c1f8f02fda4bf0a14bf306c5086a29ad445?short_path=1dd9b41#diff-1dd9b41c1d07a52069cc813ecb21901ad48aa5fd4b5cccf6c664930d42e92449).

> 2.1: "Recent estimates suggest..." Any ideas on a formal citation for this point?

Nope, I haven't found a good source.

> 7.1.1: Mostly just curiosity: Why does Firefox get the only citation for this behavior when Chrome essentially does the same thing by default in its current DoH autoupgrade?

I wasn't aware of any NXDOMAIN fallback in Chrome.  Is this documented somewhere?

**Comment by ericorth** [comment]
> > 7.1.1: Mostly just curiosity: Why does Firefox get the only citation for this behavior when Chrome essentially does the same thing by default in its current DoH autoupgrade?
> 
> I wasn't aware of any NXDOMAIN fallback in Chrome. Is this documented somewhere?

In the default autoupgrade mode (as opposed to when users/admins have selected a specific DoH provider), Chrome will retry with Do53 any time it fails to find any results for a query, including on NXDOMAIN.  This is kinda mentioned (although not super clearly) here: https://blog.chromium.org/2020/05/a-safer-and-more-private-browsing-DoH.html (second paragraph under "Responsibly deploying DNS-over-HTTPS")

This has been a very successful mitigation for any cases where Chrome's autoupgrade behavior would have otherwise messed with enterprises relying on interception to enable split-horizon behavior.  I have only seen one or two bugs from enterprises broken with a setup relying on split-horizoning a domain name with separate local and global records.

**Comment by bemasc** [comment]
OK, good to know.  Interestingly, without NXDOMAIN fallback, even baseline DDR would break that use case.

Draft 00 is now out.  Thanks for improving it!
